version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - user-service
      - product-service

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4001:4001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "4002:4002"
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "4003:4003"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
